export const jugadoresBoca = [
  "SERGIO ROMERO",
  "LEANDRO BREY",
  "JAVIER GARCIA",
  "FACUNDO RONCAGLIA",
  "AGUSTÍN SÁNDEZ",
  "NICOLÁS FIGAL",
  "MARCOS ROJO",
  "LUIS ADVINCULA",
  "FRANK FABRA",
  "VALENTÍN BARCO",
  "NICOLÁS VALENTINI",
  "BRUNO VALDEZ",
  "GABRIEL ARANDA",
  "LAUTARO DI LOLLO",
  "MARCELO WEIGANDT",
  "GUILLERMO FERNÁNDEZ",
  "OSCAR ROMERO",
  "MARTIN PAYERO",
  "ESTEBAN ROLÓN",
  "DIEGO GONZALEZ",
  "EZEQUIEL FERNÁNDEZ CARBALLO",
  "ALAN VARELA",
  "EXEQUIEL ZEBALLOS",
  "DARÍO BENEDETTO",
  "MIGUEL ÁNGEL MERENTIEL",
  "JAVIER MORALES",
  "NORBERTO BRIASCO",
  "NICOLÁS ORSINI",
  "LUIS VÁZQUEZ",
  "LUCA LANGONI",
];

export const jugadoresRiver = [
  "Franco Armani",
  "Ezequiel Centurión",
  "Lucas Lavagnino",
  "Robert Rojas",
  "Ramiro Funes Mori",
  "Jonatan Maidana",
  "David Martínez",
  "Enzo Díaz",
  "Leandro González Pirez",
  "Marcelo Andrés Herrera",
  "Paulo Díaz",
  "Milton Casco",
  "Emanuel Mammana",
  "Bruno Zuculini",
  "Agustín Palavecino",
  "Ignacio Fernández",
  "Nicolás De La Cruz",
  "Esequiel Barco",
  "Matías Kranevitter",
  "Enzo Pérez",
  "José Paradela",
  "Rodrigo Aliendro",
  "Santiago Simón",
  "Facundo Colidio",
  "Matías Suárez",
  "Miguel Borja",
  "Salomón Rondón",
  "Pablo Solari",
];

export const jugadoresArgentina = [
  "Emiliano Martínez",
  "Walter Benítez",
  "Gerónimo Rulli",
  "Cristian Romero",
  "Facundo Medina",
  "Leonardo Balerdi",
  "Germán Pezzella",
  "Nicolás Otamendi",
  "Marcos Acuña",
  "Nicolás Tagliafico",
  "Nahuel Molina",
  "Enzo Fernández",
  "Guido Rodríguez",
  "Leandro Paredes",
  "Alexis Mac Allister",
  "Rodrigo de Paul",
  "Exequiel Palacios",
  "Thiago Almada",
  "Giovani Lo Celso",
  "Facundo Buonanotte",
  "Nicolás González",
  "Alejandro Garnacho",
  "Lionel Messi",
  "Lucas Ocampos",
  "Ángel Di María",
  "Julián Álvarez",
  "Giovanni Simeone",
];
