export const jugadoresBoca = [
  "4 Facundo Roncaglia",
  "29 Nicolás Figal",
  "6 Marcos Rojo",
  "15 Nicolás Valentini",
  "17 Luis Advíncula",
  "18 Frank Fabra",
  "19 Valentín Barco",
  "25 Bruno Valdez",
  "35 Nahuel Genéz",
  "41 Lautaro Di Lollo",
  "57 Marcelo Weigandt",
  "50 Aaron Anselmino",
  "42 Lucas Blondel",
  "3 Marcelo Saracchi",
  "5 Alan Varela",
  "8 Guillermo Pol Fernández",
  "14 Esteban Rolón",
  "20 Juan Ramírez",
  "21 Ezequiel Fernández",
  "23 Diego González",
  "36 Cristian Medina",
  "31 Brandon Cortés",
  "49 Rodrigo Montes",
  "30 Román Rodríguez",
  "49 Jorman Campuzano",
  "5 Ezequiel Bullaude",
  "7 Exequiel Zeballos",
  "9 Darío Benedetto",
  "27 Nicolás Orsini",
  "29 Norberto Briasco",
  "41 Luca Langoni",
  "16 Miguel Merentiel",
  "11 Lucas Janson"
];

export const jugadoresRiver =  [
  "3 Ramiro Funes Mori",
  "4 Jonatan Maidana",
  "6 Héctor David Martínez",
  "14 Leandro González Pirez",
  "15 Marcelo Andrés Herrera",
  "17 Paulo Díaz",
  "20 Milton Casco",
  "21 Tomás Lecanda",
  "23 Emanuel Mammana",
  "13 Enzo Díaz",
  "5 Bruno Zuculini",
  "8 Agustín Palavecino",
  "26 Ignacio Fernández",
  "11 Nicolás De La Cruz",
  "24 Enzo Pérez",
  "10 Manuel Lanzini",
  "29 Rodrigo Aliendro",
  "31 Santiago Simón",
  "22 Matías Kranevitter",
  "19 Claudio Echeverri",
  "7 Matías Suárez",
  "9 Miguel Borja",
  "16 Facundo Colidio",
  "18 Lucas Beltrán",
  "25 Salomón Rondón",
  "36 Pablo Solari",
  "21 Esequiel Barco"
];

export const jugadoresArgentina =  [
  "26 Nahuel Molina",
  "4 Gonzalo Montiel",
  "13 Cristian Romero",
  "6 Germán Pezzella",
  "19 Nicolás Otamendi",
  "25 Lisandro Martínez",
  "8 Marcos Acuña",
  "3 Nicolás Tagliafico",
  "2 Juan Foyth",
  "7 Rodrigo De Paul",
  "5 Leandro Paredes",
  "20 Alexis Mac Allister",
  "18 Guido Rodríguez",
  "17 Alejandro Gómez",
  "24 Enzo Fernández",
  "14 Exequiel Palacios",
  "16 Thiago Almada",
  "11 Ángel Di María",
  "22 Lautaro Martínez",
  "9 Julián Álvarez",
  "21 Paulo Dybala",
  "15 Ángel Correa",
  "10 Lionel Messi"
];

